use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.4'

# Configuring Pod with statically linked Frameworks
use_frameworks! :linkage => :static

# Move RNFirebaseAsStaticFramework here (if you're using it)
# $RNFirebaseAsStaticFramework = true

# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

target 'colinMobileXmas' do  # <-- This block starts here
  # pod 'gRPC-Core', '1.28.2' # Use a version that might work for you.
  # pod 'Firebase/Core'
  # pod 'Firebase/Storage'

  config = use_native_modules!
  # flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # :hermes_enabled => flags[:hermes_enabled],
    # :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|  # <-- This block starts inside the previous block
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end  # <-- This block ends here
end  # <-- The 'colinMobileXmas' block should end here

